#if !canImport(ObjectiveC)
import XCTest

extension InputRepresentationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InputRepresentationTests = [
        ("testAnotherMismatch", testAnotherMismatch),
        ("testLanguageMatch", testLanguageMatch),
        ("testMatch", testMatch),
        ("testMismatch", testMismatch),
        ("testRootMismatch", testRootMismatch),
        ("testUnused", testUnused),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(InputRepresentationTests.__allTests__InputRepresentationTests),
    ]
}
#endif
